title: Michael Fortune
logo: /assets/img/logo.png
description: Mechanical Engineer
  _in transition to_
  Software and Data Engineering
show_downloads: false
google_analytics: G-ZLK2GHB055
color-scheme: auto
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

# You can find fonts from https://iconify.design or https://fontawesome.com. Below is just an example illustrating how to use custom icons
sidebar:
  - name: Projects
    icon: <i class="fa-regular fa-lightbulb"></i>
    link: https://scholar.google.com/citations?user=zR6afi8AAAAJ
  - name: Blog
    icon: <i class="fa-solid fa-pen"></i>
    link: https://www.bodunhu.com/blog/
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/fortune1991
  - name: Linkedin
    icon: <i class="fa-brands fa-linkedin"></i>
    link: https://github.com/fortune1991
  - name: CV
    icon: <i class="fa-solid fa-briefcase"></i>
    link: https://twitter.com/BodunHu
  - name: E-mail
    icon: <i class="fa-solid fa-envelope"></i>
    link: mailto:michaelfortune91@gmail.com

# https://github.com/github/pages-gem/issues/399#issuecomment-301827749
# When running locally, we run into the following error —
# GitHub Metadata: No GitHub API authentication could be found. Some fields may be missing or have incorrect data.
# adding this avoids it
github: [metadata]
